spring.application.name=financial-ai-analyzer-backend

gemini.api.key=AQ.Ab8RN6Kt69IMTtqhgzCn3j_2qoMmp09rY3or-Ax3Ocb8Hf4Urg
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.model=nomic-embed-text
spring.ai.ollama.chat.options.model=qwen3:4b


#=========PG-Vector Config===========
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
#====================================
spring.datasource.url=jdbc:postgresql://localhost:5432/financial_ai
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect