spring.application.name=financial-ai-analyzer-backend

gemini.api.key=AQ.Ab8RN6Kt69IMTtqhgzCn3j_2qoMmp09rY3or-Ax3Ocb8Hf4Urg

spring.datasource.url=jdbc:postgresql://localhost:5432/financial_ai
spring.datasource.username=postgres
spring.datasource.password=Savitriom@1915
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect